# ======== CONFIGURATION SPRING BOOT ========

# Désactiver le cache Thymeleaf
spring.thymeleaf.cache=false

# Emplacement par défaut des templates
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# Charset d'encodage
spring.thymeleaf.encoding=UTF-8
spring.web.resources.static-locations=classpath:/static/

# BDD
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.config.import=optional:file:.env[.properties]
# EN PRODUCTION
# spring.jpa.hibernate.ddl-auto=update EN PRODUCTION

# EN DEV
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ======== INFORMATIONS PROJET ========

spring.application.name=rss25SB
logging.level.org.springframework.web=DEBUG
server.port=8080